---
- name: Gathering facts on instance
  os_server_facts:
    auth: "{{ os_auth_tenant }}"
    server: "{{ server_name }}"
    validate_certs: False
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
  register: instance
  tags:
    - instance_inventory


- name: add instance to ansible inventory
  add_host:
     name: os_instance
     groups: openstack
     ansible_host: "{{instance.ansible_facts.openstack_servers.0.public_v4}}"
     ansible_user: cloud-user
     ansible_become: true
  tags:
    - instance_inventory


- name: Wait for instance to come up
  wait_for:
    port=22
    delay=1
    timeout=300
    host="{{instance.ansible_facts.openstack_servers.0.public_v4}}"
  tags:
    - instance_inventory

