---
-  name: Ensure user admin is assigned to role member for the projects
   os_user_role:
     auth: "{{ os_auth }}"
     state: "{{ state }}"
     user: "admin"
     role: member
     project: "{{ project_name }}"
     validate_certs: False
   environment:
     OS_IDENTITY_API_VERSION: 3
     OS_PROJECT_DOMAIN_NAME: Default
     OS_USER_DOMAIN_NAME: Default
   tags: role

