---
rhel_image: rhel7-updated
pxe_image: pxeboot
keypair: ansible
flavor_undercloud: undercloud
flavor_controller: overcloud-controller
flavor_compute: overcloud-compute
flavor_ceph: overcloud-ceph
flavor_hci: overcloud-hci
ceph_disk_count: 1
ceph_disk_size: 100
cloud_admin: admin
admin_password: Passw0rd
admin_project: admin
os_auth: https://openstack.home.lab:13000/v2.0
network_pxe: pxe
network_intapi: internalapi
network_tenant: tenant
network_storage: storage
network_storagemgmt: storagemgmt
network_infra_ext: provider2
ntp_server: 172.31.8.1
dns_server: 172.31.8.1



controller_networks:
  - pxe
  - internalapi
  - tenant
  - storage
  - storagemgmt
compute_networks:
  - pxe
  - internalapi
  - tenant
  - storage
ceph_networks:
  - pxe
  - storage
  - storagemgmt
hci_networks:
  - pxe
  - internalapi
  - tenant
  - storage
  - storagemgmt

networks:
  pxe:
    name: "pxe"
    cidr: "172.16.0.0/24"
    netmask_length: 24
    prefix: "172.16.0"
    port_security_enabled: false
    no_security_groups: true
    enable_dhcp: false
    no_gateway_ip: true
  internalapi:
    name: "internalapi"
    cidr: "172.16.1.0/24"
    prefix: "172.16.1"
    port_security_enabled: true
    no_security_groups: true
    enable_dhcp: false
    no_gateway_ip: true
  storage:
    name: "storage"
    cidr: "172.16.3.0/24"
    prefix: "172.16.3"
    port_security_enabled: true
    no_security_groups: true
    enable_dhcp: false
    no_gateway_ip: true
  storagemgmt:
    name: "storagemgmt"
    cidr: "172.16.4.0/24"
    prefix: "172.16.4"
    port_security_enabled: true
    no_security_groups: true
    enable_dhcp: false
    no_gateway_ip: true
  tenant:
    name: "tenant"
    cidr: "172.16.2.0/24"
    prefix: "172.16.2"
    port_security_enabled: true
    no_security_groups: true
    enable_dhcp: false
    no_gateway_ip: true


quota:
  ram: 131072
  vcpus: 100
  instances: 16
  ports: 128

