---
- name: upload keypair for ansible server
  os_keypair:
    auth: "{{ os_auth_tenant }}"
    state: "{{ state }}"
    name: hextupleo_pub_key
    validate_certs: False
    public_key: "{{ id_rsa_pub }}"
  environment:
    OS_IDENTITY_API_VERSION: 3
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
  tags: keypair

