---
-  name: Ensure projects is "{{ state }}"
   os_project:
     auth:
       auth_url: "{{ os_auth }}"
       username: "{{ cloud_admin }}"
       password: "{{ admin_password }}"
       project_name: "{{ admin_project }}"
     state: "{{ state }}"
     endpoint_type: admin
     name: "{{ project_name }}"
     enabled: True
     validate_certs: False
   tags: project

