---
#-  name: Set up quotas
#   os_quota:
#     auth:
#       auth_url: "{{ os_auth }}"
#       username: "{{ cloud_admin }}"
#       password: "{{ admin_password }}"
#       project_name: "{{ admin_project }}"
#     endpoint_type: admin
#     name: "{{ project_name  }}"
#     cores: "{{ quota.vcpus }}"
#     ram: "{{ quota.ram }}"
#     instances: "{{ quota.instances }}"
#     port: "{{ quota.ports }}"
#     state: "{{ state }}"
#     validate_certs: False
#   tags: 
#    - quota
# there is some issues in this module - I either have problem with ssl or it's trying to reach my OpenStack via internalAPI


  - name: update quota with shell
    shell: openstack --os-auth-url "{{ os_auth }}" --os-project-name "{{ admin_project }}" --os-username "{{ cloud_admin }}" --os-password "{{ admin_password }}" --insecure quota set --instances "{{ quota.instances }}" --cores "{{ quota.vcpus }}" --ram "{{ quota.ram }}" --ports "{{ quota.ports }}" "{{ project_name }}"
    tags:
     - quota

