---
-  name: Ensure neutron networks for {{ project_name }} are {{ state }}
   os_network:
     auth:
       auth_url: "{{ os_auth }}"
       username: "{{ project_name }}"
       password: "{{ project_password }}"
       project_name: "{{ project_name }}"
     state: "{{ state }}"
     name: "{{ item.value.name }}"
     validate_certs: False
   with_dict: "{{ networks }}"
   tags: 
     - networks


