---
    
- name: Gathering facts on undercloud instance
  os_server_facts:
    auth:
       auth_url: "{{ os_auth }}"
       username: "{{ project_name }}"
       password: "{{ project_password }}"
       project_name: "{{ project_name }}"
    server: undercloud
    validate_certs: False
  register: undercloud
  tags:
    - undercloud

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 1

- name: add undercloud to ansible inventory
  add_host:
     name: undercloud
     groups: openstack
     ansible_host: "{{undercloud.ansible_facts.openstack_servers.0.public_v4}}"
     ansible_user: cloud-user
     ansible_become: true
  tags:
    - undercloud


- name: verify undercloud is up and reachable (Ignore errors set for el7.2)
  command: >
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no
    cloud-user@{{undercloud.ansible_facts.openstack_servers.0.public_v4}} true
  register: result
  until: result|success
  retries: 10
  delay: 5
  tags:
    - undercloud
  ignore_errors: true
  when: not update_guest_packages | bool

- name: Make sure undercloud is restarted (el7.2 issue where sshd doesn't start on first boot)
  shell: >
     openstack --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}"
     --os-username "{{ project_name }}" --os-password "{{ project_password }}"
     --insecure server reboot undercloud
  #retries: 2
  delay: 1
  ignore_errors: true
  when: not update_guest_packages | bool

- name: verify undercloud is up and reachable (again)
  command: >
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no
    cloud-user@{{undercloud.ansible_facts.openstack_servers.0.public_v4}} true
  register: result
  until: result|success
  retries: 10
  delay: 5
  tags:
    - undercloud
  ignore_errors: true
