---
  - name: Create security group
    os_security_group:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       state: present
       name: hextupleO
       description: security group for hextupleO servers
       validate_certs: False

  - name: Add rules for icmp - ping
    os_security_group_rule:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       security_group: hextupleO
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

  - name: Add rules for all tcp ports
    os_security_group_rule:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       security_group: hextupleO
       protocol: tcp
       port_range_min: 1
       port_range_max: 65535
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

  - name: Add rules for all udp ports
    os_security_group_rule:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       security_group: hextupleO
       protocol: udp
       port_range_min: 1
       port_range_max: 65535
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

