parameter_defaults:
  CephConfigOverrides:
    journal_size: 5120
    max_open_files: 131072
    osd_pool_default_size: 1
    osd_pool_default_min_size: 1
    osd_pool_default_pg_num: 16
    osd_pool_default_pgp_num: 16
  CephAnsibleDisksConfig:
    osd_scenario: collocated
    dmcrypt: False
    devices:
      - /dev/sdb
  CephPoolDefaultPgNum: 16
  # !! Dallas Hackfest - parameter below is really important if you enabled CloudDomain in undercloud.conf. The parameter below is a workaround to not hit https://bugzilla.redhat.com/show_bug.cgi?id=1507888
  CephAnsibleExtraConfig:
    mon_use_fqdn: true
