---
- name: Learn all the subnets in the project
  os_subnets_info:
    auth: "{{ os_auth_tenant }}"
    validate_certs: False
    filters:
      project_id: "{{ item.id }}"
  with_items:
    - "{{ project_info.openstack_projects }}"
  register: project_subnets
  

  tags:
    - subnets

- name: Show openstack subnets
  debug:
     msg: "{{ project_subnets.results.0 }}"
  tags:
     - subnets


- name: Ensure neutron subnets are "{{ state }}"
  os_subnet:
    auth: "{{ os_auth_tenant }}"
    state: "{{ state }}"
    name: "{{ item.name }}"
    validate_certs: False
  with_items:
    - "{{ project_subnets.results.0.openstack_subnets }}"

  tags:
    - subnets

