---

# undercloud
############
  - name: disable security on provisioning nic for undercloud
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}" --os-username "{{ project_name }}" --os-password "{{ project_password }}" --insecure port-update pxe-undercloud --port-security-enabled=False

# controller
############


  - name: disable security on ports for controllers
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}" --os-username "{{ project_name }}" --os-password "{{ project_password }}" --insecure port-update "{{ item.0 }}-controller{{ item.1 }}" --port-security-enabled=False
    with_nested:
      - "{{ controller_networks }}"
      - "{{lookup('sequence', 'count={{ controller_count }}',wantlist=true)}}"

  - name: disable security on external nic for controllers
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ cloud_admin }}" --os-username "{{ cloud_admin }}" --os-password "{{ admin_password }}" --insecure port-update {{ project_name }}-external-controller"{{ item }}" --port-security-enabled=False
    with_sequence:
       count="{{ controller_count }}"



# compute
############


  - name: disable security on ports for compute
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}" --os-username "{{ project_name }}" --os-password "{{ project_password }}" --insecure port-update "{{ item.0 }}-compute{{ item.1 }}" --port-security-enabled=False
    with_nested:
      - "{{ compute_networks }}"
      - "{{lookup('sequence', 'count={{ compute_count }}',wantlist=true)}}"


# ceph
############


  - name: disable security on ports for ceph
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}" --os-username "{{ project_name }}" --os-password "{{ project_password }}" --insecure port-update "{{ item.0 }}-ceph{{ item.1 }}" --port-security-enabled=False
    with_nested:
      - "{{ ceph_networks }}"
      - "{{lookup('sequence', 'count={{ ceph_count }}',wantlist=true)}}"



# hci
############



  - name: disable security on ports for hci
    shell: neutron --os-auth-url "{{ os_auth }}" --os-project-name "{{ project_name }}" --os-username "{{ project_name }}" --os-password "{{ project_password }}" --insecure port-update "{{ item.0 }}-hci{{ item.1 }}" --port-security-enabled=False
    with_nested:
      - "{{ hci_networks }}"
      - "{{lookup('sequence', 'count={{ hci_count }}',wantlist=true)}}"



