---
- name: Generating openstack rc file for your convenience
  pause:
    seconds: 1
    prompt: |
       for key in $( set | awk '{FS="="}  /^OS_/ {print $1}' ); do unset $key ; done
       export NOVA_VERSION=1.1
       export COMPUTE_API_VERSION=1.1
       export OS_USERNAME={{ project_name }}
       export OS_PROJECT_NAME={{ project_name }}
       export OS_USER_DOMAIN_NAME={{ clouds.devstack.auth.domain_name }}
       export OS_PROJECT_DOMAIN_NAME={{ clouds.devstack.auth.domain_name }}
       export OS_NO_CACHE=True
       export OS_CLOUDNAME={{ project_name }}
       export PYTHONWARNINGS='ignore:Certificate has no, ignore:A true SSLContext object is not available'
       export OS_AUTH_TYPE=password
       export OS_PASSWORD={{ project_password }}
       export OS_AUTH_URL={{ clouds.devstack.auth.auth_url }}
       export OS_IDENTITY_API_VERSION=3
       export OS_COMPUTE_API_VERSION=2.latest
       export OS_IMAGE_API_VERSION=2
       export OS_VOLUME_API_VERSION=3
       export OS_REGION_NAME=regionOne
       # Add OS_CLOUDNAME to PS1
       if [ -z "${CLOUDPROMPT_ENABLED:-}" ]; then
           export PS1=${PS1:-""}
           export PS1=\${OS_CLOUDNAME:+"(\$OS_CLOUDNAME)"}\ $PS1
           export CLOUDPROMPT_ENABLED=1
       fi

