---

# undercloud
############

  - name: create pxe port for undercloud
    os_port:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       state: "{{ state }}"
       name: pxe-undercloud
       network: "{{ network_pxe }}"
       no_security_groups: True
       validate_certs: False


# controller
############


  - name: Ensure neutron ports for controller are enabled
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ project_name }}"
        password: "{{ project_password }}"
        project_name: "{{ project_name }}"
      state: "{{ state }}"
      name: "{{ item.0 }}-controller{{ item.1 }}"
      network: "{{ item.0 }}"
      no_security_groups: True
      validate_certs: False
    with_nested:
      - "{{ controller_networks }}"
      - "{{lookup('sequence', 'count={{ controller_count }}',wantlist=true)}}"


  - name: create external port for controllers
    os_port:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       state: "{{ state }}"
       name: "{{ project_name }}-external-controller{{ item }}"
       network: "{{ lookup('csvfile', '#{{ available.stdout }} file=files/networks.csv delimiter=, col=1') }}"
       no_security_groups: True
       validate_certs: False
    with_sequence:
       count="{{ controller_count }}"



# compute
############


  - name: Ensure neutron ports for compute are enabled
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ project_name }}"
        password: "{{ project_password }}"
        project_name: "{{ project_name }}"
      state: "{{ state }}"
      name: "{{ item.0 }}-compute{{ item.1 }}"
      network: "{{ item.0 }}"
      no_security_groups: True
      validate_certs: False
    with_nested:
      - "{{ compute_networks }}"
      - "{{lookup('sequence', 'count={{ compute_count }}',wantlist=true)}}"



# ceph
############


  - name: Ensure neutron ports for ceph are enabled
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ project_name }}"
        password: "{{ project_password }}"
        project_name: "{{ project_name }}"
      state: "{{ state }}"
      name: "{{ item.0 }}-ceph{{ item.1 }}"
      network: "{{ item.0 }}"
      no_security_groups: True
      validate_certs: False
    with_nested:
      - "{{ ceph_networks }}"
      - "{{lookup('sequence', 'count={{ ceph_count }}',wantlist=true)}}"




# hci
############


  - name: Ensure neutron ports for controller are enabled
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ project_name }}"
        password: "{{ project_password }}"
        project_name: "{{ project_name }}"
      state: "{{ state }}"
      name: "{{ item.0 }}-hci{{ item.1 }}"
      network: "{{ item.0 }}"
      no_security_groups: True
      validate_certs: False
    with_nested:
      - "{{ hci_networks }}"
      - "{{lookup('sequence', 'count={{ hci_count }}',wantlist=true)}}"



