---
- name: Learn all the networks in the project for the project
  os_networks_info:
    auth: "{{ os_auth_tenant }}"
    validate_certs: False
    filters:
      project_id: "{{ item.id }}"
  with_items:
    - "{{ project_info.openstack_projects }}"
  register: project_networks

  tags:
    - networks

- name: Show openstack networks
  debug:
     msg: "{{ project_networks.results.0.openstack_networks }}"
  tags:
     - networks


- name: Ensure neutron networks are "{{ state }}"
  os_network:
    auth: "{{ os_auth_tenant }}"
    state: "{{ state }}"
    name: "{{ item.id }}"
    port_security_enabled: False
    validate_certs: False
  with_items:
    - "{{ project_networks.results.0.openstack_networks }}"

  tags:
    - networks

