---
-  name: Give external IP  back to pool
   shell: grep ",{{ project_name }}$"  files/networks.csv |  awk -F "," {'print substr($1,2) '}
   register: taken

- replace:
    path: files/networks.csv
    regexp: "^#{{ taken.stdout }}"
    replace: "{{ taken.stdout }}"



- replace:
    path: files/networks.csv
    regexp: ",{{ project_name }}$"
    replace: ""

