---
  - name: Add rules for icmp - ping
    os_security_group_rule:
       auth: "{{ os_auth_tenant }}"
       security_group: default
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

  - name: Add rules for tcp port 22
    os_security_group_rule:
       auth: "{{ os_auth_tenant }}"
       security_group: default
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

