---
  - name: Add rules for icmp - ping
    os_security_group_rule:
       auth:
         auth_url: "{{ clouds.devstack.auth.auth_url }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
         domain_id: "{{ clouds.devstack.auth.domain_name }}"
       security_group: default
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

  - name: Add rules for tcp port 22
    os_security_group_rule:
       auth:
         auth_url: "{{ clouds.devstack.auth.auth_url }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
         domain_id: "{{ clouds.devstack.auth.domain_name }}"
       security_group: default
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False

